[jobs.lab1]
image = { source = "dockerfile", path = ".", tag = "lab1" }
run = [
    "java Main -llvm $input -o $ir",
]

[jobs.lab2]
image = { source = "dockerfile", path = ".", tag = "lab2" }
run = [
    "java Main -llvm $input -o $ir",
]

[jobs.lab3]
image = { source = "dockerfile", path = ".", tag = "lab3" }
run = [
    "java Main -llvm $input -o $ir",
]

[jobs.lab4]
image = { source = "dockerfile", path = ".", tag = "lab4" }
run = [
    "java Main -llvm $input -o $ir",
]

[jobs.lab5]
image = { source = "dockerfile", path = ".", tag = "lab5" }
run = [
    "java Main -llvm $input -o $ir",
]

[jobs.lab6]
image = { source = "dockerfile", path = ".", tag = "lab6" }
run = [
    "java Main -llvm $input -o $ir",
]

[jobs.lab7]
image = { source = "dockerfile", path = ".", tag = "lab7" }
run = [
    "java Main -llvm $input -o $ir",
]

[jobs.lab8]
image = { source = "dockerfile", path = ".", tag = "lab8" }
run = [
    "java Main -llvm $input -o $ir",
]

[jobs.short_circuit]

image = { source = "dockerfile", path = ".", tag = "short_circuit" }
run = [
    "java Main -llvm $input -o $ir",
]